version: "3.7"

services:
  vault:
    image: luanapp/vault-consul:1.4
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
    ports:
      - 8200:8200
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: server
    networks:
      vault-public:
        aliases:
          - vault.cluster
      consul:
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_CONFIG: '{"api_addr": "http://0.0.0.0:8200", "cluster_address": "vault.cluster:8200", "cluster_name": "LuanaSecurePlace", "disable_cache": true, "disable_mlock": true, "listener": {"tcp": {"address": "0.0.0.0:8200", "cluster_address": "vault.cluster:8200", "tls_disable": true}}, "storage": {"consul": {"address": "127.0.0.1:8500", "path": "vault/", "scheme": "http"}}, "ui": true}'
      CONSUL_CONFIG: '{"leave_on_terminate":true, "datacenter":"dc1", "node_name": "vault", "retry_join": ["consul.cluster"], "data_dir": "vault/"'

volumes:
  vault_data:

networks:
  vault-public:
    external: true
  consul:
    external: true
